"""initial_schema

Revision ID: 921892d5aaf7
Revises: 
Create Date: 2026-09-02 22:05:28.478351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921892d5aaf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('numeric_id', sa.Integer(), nullable=True),
    sa.Column('plant_species', sa.String(length=100), nullable=False),
    sa.Column('disease_name', sa.String(length=150), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diseases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diseases_numeric_id'), ['numeric_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_diseases_plant_species'), ['plant_species'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('active_2fa_otp', sa.String(length=10), nullable=True),
    sa.Column('otp_expiry_time', sa.DateTime(), nullable=True),
    sa.Column('active_session_id', sa.String(length=64), nullable=True),
    sa.Column('failed_otp_attempts', sa.Integer(), nullable=False),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_active_session_id'), ['active_session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email_address'), ['email_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    op.create_table('disease_history_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.String(length=50), nullable=False),
    sa.Column('disease_name', sa.String(length=150), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('s3_storage_uri', sa.String(length=500), nullable=False),
    sa.Column('bounding_box_json', sa.Text(), nullable=True),
    sa.Column('diagnosis_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disease_history_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disease_history_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_history_logs_user_id'), ['user_id'], unique=False)

    op.create_table('remedies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.String(length=50), nullable=False),
    sa.Column('remedy_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('application_instructions', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remedies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedies_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedies_id'))

    op.drop_table('remedies')
    with op.batch_alter_table('disease_history_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disease_history_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_disease_history_logs_id'))

    op.drop_table('disease_history_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email_address'))
        batch_op.drop_index(batch_op.f('ix_users_active_session_id'))

    op.drop_table('users')
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diseases_plant_species'))
        batch_op.drop_index(batch_op.f('ix_diseases_numeric_id'))
        batch_op.drop_index(batch_op.f('ix_diseases_id'))

    op.drop_table('diseases')
    # ### end Alembic commands ###
